### ISSUE TITLE
Method for making benchmark training/test splits and using CD-HIT for redundancy filtering missing

### ISSUE THREAD

**Issue by mennohie** [AbeelLab/safpred#1]
In method 2.1.1 the method for parsing the swissprot dataset into 30 benchmark train/test splits is not provided in the codebase. The step using CD-HIT to filter out redundant proteins is also missing.

For proper reproduction of paper results these methods are required.

**Comment by aysunrhn** [comment]
I've added the CDHIT command to the README.md file now. 

https://github.com/AbeelLab/safpred/blob/54a5fe4ea1e0333810ff4ff82ab236107fff50a9/README.md?plain=1#L87C1-L92C4
